# Generated by Django 5.2.1 on 2025-05-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
