# Generated by Django 5.2.1 on 2025-05-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0005_scan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='domain',
            new_name='scan_id',
        ),
        migrations.AddField(
            model_name='scan',
            name='url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
