# Generated by Django 5.2.1 on 2025-05-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0006_rename_domain_scan_scan_id_scan_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.IntegerField(),
        ),
    ]
