# Generated by Django 5.2.1 on 2025-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0007_alter_scan_scan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.CharField(max_length=100),
        ),
    ]
