# Generated by Django 5.2.1 on 2025-05-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0008_alter_scan_scan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
