# Generated by Django 5.2.1 on 2025-05-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0009_scan_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='status',
        ),
    ]
