# Generated by Django 5.2.3 on 2025-08-28 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0011_scan_leak_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='id',
        ),
        migrations.AddField(
            model_name='scan',
            name='zap_scan_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=255)),
                ('risk', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Informational', 'Informational')], max_length=20)),
                ('confidence', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('solution', models.TextField(blank=True)),
                ('reference', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('attack', models.TextField(blank=True)),
                ('param', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='secure.scan')),
            ],
        ),
    ]
