# Generated by Django 5.2.3 on 2025-08-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0012_remove_scan_id_scan_zap_scan_id_alter_scan_scan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='leak_data',
        ),
    ]
