# Generated by Django 5.2.3 on 2025-08-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0013_remove_scan_leak_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
