# Generated by Django 5.2.3 on 2025-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0014_scan_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='zap_scan_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
