# Generated by Django 5.2.3 on 2025-08-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0015_alter_scan_zap_scan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='remark',
            field=models.TextField(blank=True),
        ),
    ]
