# Generated by Django 5.2.3 on 2025-08-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0016_scan_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='marked_as_false_positive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
