# Generated by Django 5.2.3 on 2025-08-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure', '0017_scanresult_marked_as_false_positive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
